### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by ChenYuYuYuYuYuT** [mwangli/jd-spider#1]
你好，下载了您的源码，自己使用更改了user-agent，cookie，现在运行出现302最开始是出现200，再运行一次就是302了。可以请教怎么更改吗，求求~

**Comment by ChenYuYuYuYuYuT** [comment]
![Uploading iwEcAqNwbmcDAQTRB4AF0QQHBrAB5TC9XebuqAX27pWv-YsAB9Jqau3kCAAJomltCgAL0gADdsI.png_720x720q90.jpg…]()

**Comment by mwangli** [comment]
被重定向的到安全验证页面了，换个时间再运行看看，把请求延迟加上，请求频率降低点不容易触发安全校验
